# Generated by Django 3.0.5 on 2020-04-11 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(default='Mexa tudo muito bem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 11, 12, 55, 29, 125333)),
        ),
    ]
